# Generated by Django 3.0.4 on 2020-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(blank=True, db_column='CONTENT', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True, db_column='DATE', null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postid',
            field=models.CharField(db_column='POSTID', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=30),
        ),
    ]
