# Generated by Django 3.0.4 on 2020-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200305_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postid',
            field=models.IntegerField(db_column='POSTID', max_length=30, primary_key=True, serialize=False),
        ),
    ]
