# Generated by Django 3.0.4 on 2020-03-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200305_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no',
            field=models.AutoField(db_column='NO', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='postid',
            field=models.IntegerField(db_column='POSTID', max_length=30),
        ),
    ]
